/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-06-26 15:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cscustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tags/header.tag", Long.valueOf(1435333042615L));
    _jspx_dependants.put("/WEB-INF/tags/script.tag", Long.valueOf(1435333042635L));
    _jspx_dependants.put("/WEB-INF/tags/dependencies.tag", Long.valueOf(1435333042606L));
    _jspx_dependants.put("/WEB-INF/tags/footer.tag", Long.valueOf(1435333042611L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      if (_jspx_meth_tags_005fdependencies_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tags_005fscript_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_tags_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-8\" id=\"activity-container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-offset-2\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"login-form\" class=\"simple_form form-horizontal\"\r\n");
      out.write("\t\t\t\t\t\t\tnovalidate=\"novalidate\" action=\"\" accept-charset=\"UTF-8\"\r\n");
      out.write("\t\t\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" /><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"authenticity_token\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"OlargpQtQGzKE+3wa9sKoPyc6HIeZ9GMmL1fUGlfwejD2OYtwTL9KjC6c6M23KmpC1L4fmfe7ZWypKn+Hxl7Yg==\" />\r\n");
      out.write("\t\t\t\t\t\t\t<br> <br> <br> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Login as Customer, Click login button</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group string required quick_start_login_api_key\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"string required col-sm-3 control-label hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"api_key\"><abbr title=\"required\">*</abbr> Project\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAPI Key</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"api_key\" name=\"api_key\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"string required form-control hidden\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"DAK5aa3e878df1d46ca9f83e27ad0dfba1f\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-group string required quick_start_login_username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"string required col-sm-3 control-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"username\"><abbr title=\"required\">*</abbr> Username</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"username\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"string required form-control\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"customer1\" disabled />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-group password required quick_start_login_password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"password required col-sm-3 control-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"password\"><abbr title=\"required\">*</abbr> Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"password required form-control\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"reset@123\" disabled />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-3 col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"commit\" value=\"Login\" id=\"login-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-success\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"hidden\" id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"h4 pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Hello <span class=\"username\"></span></strong>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger pull-right\" id=\"logout-btn\">Logout</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t<div id=\"video-container\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Video</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"video\" id=\"incoming-video\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"video\" id=\"outgoing-video\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t<div class=\"hidden\" id=\"incoming-call\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Incoming Call</h4>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"username-incoming\"></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-toolbar\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-success\" id=\"answer-call-btn\">Answer\r\n");
      out.write("\t\t\t\t\t\t\t\tCall</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-warning\" id=\"reject-call-btn\">Reject\r\n");
      out.write("\t\t\t\t\t\t\t\tCall</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"hidden\" id=\"call-connected\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Call Connected</h4>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"username-connected\"></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-toolbar\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-danger\" id=\"end-call-btn\">End\r\n");
      out.write("\t\t\t\t\t\t\t\tCall</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-warning\" id=\"hold-call-btn\">Hold\r\n");
      out.write("\t\t\t\t\t\t\t\tCall</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-success hidden\" id=\"resume-call-btn\">Resume\r\n");
      out.write("\t\t\t\t\t\t\t\tCall</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"row\">\r\n");
      out.write("\t\t\t<div id=\"chat-container\" class=\"hidden\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t<label for=\"chat-messages\" class=\"bg-warning\">Chat message:</label>\r\n");
      out.write("\t\t\t\t\t<div id=\"chat-messages\" class=\"bg-info\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"chat-input\" class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"chat-contacts\">Select Customer to send message</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"chat-contacts\" id=\"chat-contacts\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\"></select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"chat-message\">Message:</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"chat-message\" id=\"chat-message\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button name=\"button\" type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\tid=\"chat-btn\">Send</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      if (_jspx_meth_tags_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tags_005fdependencies_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tags:dependencies
    org.apache.jsp.tag.webdependencies_tag _jspx_th_tags_005fdependencies_005f0 = (new org.apache.jsp.tag.webdependencies_tag());
    _jsp_instancemanager.newInstance(_jspx_th_tags_005fdependencies_005f0);
    _jspx_th_tags_005fdependencies_005f0.setJspContext(_jspx_page_context);
    _jspx_th_tags_005fdependencies_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tags_005fdependencies_005f0);
    return false;
  }

  private boolean _jspx_meth_tags_005fscript_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tags:script
    org.apache.jsp.tag.webscript_tag _jspx_th_tags_005fscript_005f0 = (new org.apache.jsp.tag.webscript_tag());
    _jsp_instancemanager.newInstance(_jspx_th_tags_005fscript_005f0);
    _jspx_th_tags_005fscript_005f0.setJspContext(_jspx_page_context);
    // /customer/cscustomer.jsp(8,0) name = src type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_tags_005fscript_005f0.setSrc("customer/cscustomer.js");
    _jspx_th_tags_005fscript_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tags_005fscript_005f0);
    return false;
  }

  private boolean _jspx_meth_tags_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tags:header
    org.apache.jsp.tag.webheader_tag _jspx_th_tags_005fheader_005f0 = (new org.apache.jsp.tag.webheader_tag());
    _jsp_instancemanager.newInstance(_jspx_th_tags_005fheader_005f0);
    _jspx_th_tags_005fheader_005f0.setJspContext(_jspx_page_context);
    _jspx_th_tags_005fheader_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tags_005fheader_005f0);
    return false;
  }

  private boolean _jspx_meth_tags_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tags:footer
    org.apache.jsp.tag.webfooter_tag _jspx_th_tags_005ffooter_005f0 = (new org.apache.jsp.tag.webfooter_tag());
    _jsp_instancemanager.newInstance(_jspx_th_tags_005ffooter_005f0);
    _jspx_th_tags_005ffooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_tags_005ffooter_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tags_005ffooter_005f0);
    return false;
  }
}
